# Generated by Django 3.0.3 on 2020-05-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
